version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: ./adeo-request-system-backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/adeo_request_system
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./adeo-request-system-backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

  frontend:
    build:
      context: ./adeo-request-system-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./adeo-request-system-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: