services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:9091  # Updated to match new backend port
    volumes:
      - ./adeo-request-system-frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "9091:3000"  # Changed to 9091
    environment:
      - ./adeo-request-system-backend/.env
    volumes:
      - ./adeo-request-system-backend:/app
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=adeodb

volumes:
  mongodb_data:
  backend_logs:
  backend_uploads: